### numpy.random

In [1]:
import numpy as np

In [3]:
# 	Random values in a given shape
np.random.rand(2,3,4)

array([[[0.77608865, 0.64535524, 0.48775612, 0.90510687],
        [0.55977783, 0.08584929, 0.93807359, 0.17092648],
        [0.63534885, 0.20358166, 0.93163566, 0.00527925]],

       [[0.73210721, 0.3737725 , 0.1814264 , 0.97454388],
        [0.60175325, 0.95065003, 0.24903675, 0.56610213],
        [0.03876465, 0.4172971 , 0.95461798, 0.8607339 ]]])

In [5]:
# Return a sample (or samples) from the “standard normal” distribution.
np.random.randn(2,3)

array([[ 1.13600366, -1.17706459, -0.58734837],
       [ 1.39618594,  0.58779154,  1.31524595]])

In [8]:
# Return random integers from low (inclusive) to high (exclusive).
np.random.randint(2,3,(2,3))

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
np.random.randint(2,3,3)

array([2, 2, 2])

In [11]:
# Random integers of type np.int between low and high, inclusive.
np.random.random_integers(2,5,3)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: This function is deprecated. Please call randint(2, 5 + 1) instead
  


array([3, 2, 2])

In [12]:
np.random.random_integers(2,5,(3,2))

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(2, 5 + 1) instead
  """Entry point for launching an IPython kernel.


array([[2, 2],
       [4, 2],
       [5, 4]])

In [13]:
# Return random floats in the half-open interval [0.0, 1.0).
np.random.random_sample([2,3])

array([[0.44047605, 0.17940459, 0.11771758],
       [0.89337909, 0.43349623, 0.0283879 ]])